name: MCRekus
version: '${project.version}'
author: '5170'
description: Main core for the MCRekus server
website: https://bestsysadmin.me
main: dev.isnow.mcrekus.MCRekus
api-version: '1.20'
softdepend:
  - PlaceholderAPI
  - Vehicles
  - DecentHolograms
  - Kingdoms
libraries:
  - org.hibernate:hibernate-core:6.2.8.Final
  - jakarta.validation:jakarta.validation-api:3.0.2
  - jakarta.persistence:jakarta.persistence-api:3.1.0
  - org.mariadb.jdbc:mariadb-java-client:3.3.3
#  - org.hibernate.validator:hibernate-validator:8.0.0.Final
  - com.h2database:h2:2.2.224
  - com.mysql:mysql-connector-j:9.0.0
  - de.exlll:configlib-paper:4.5.0
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - com.github.ben-manes.caffeine:jcache:3.1.8
  - org.hibernate:hibernate-jcache:6.2.8.Final