name: MCRekus
version: '${project.version}'
author: '5170'
description: Main core for the MCRekus server
website: https://bestsysadmin.me
main: dev.isnow.mcrekus.MCRekus
api-version: '1.20'
softdepend:
  - PlaceholderAPI
  - Vehicles
  - DecentHolograms
  - Kingdoms
libraries:
  - io.ebean:ebean:14.6.0
  - io.ebean:ebean-ddl-generator:14.6.0
  - org.mariadb.jdbc:mariadb-java-client:3.3.3
  - com.h2database:h2:2.2.224
  - com.mysql:mysql-connector-j:8.3.0
  - de.exlll:configlib-paper:4.5.0
  - com.github.ben-manes.caffeine:caffeine:3.1.8